image:
  file: .gitpod.Dockerfile

tasks:
  - name: Set up Node and IC SDK
    init: |
      # Command to set up IC SDK
      'sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"'

      # Commands for Node.js installation
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
      source ~/.nvm/nvm.sh
      nvm install --lts